### ISSUE TITLE
4 tests fail when running the unit tests

### ISSUE THREAD

**Issue by adamryczkowski** [hadley/evaluate#72] opened 2016-08-31 17:38 UTC
Are those failures by design? Here is an output:

```
==> Sourcing R files in 'tests' directory

1. Failure: return value of value handler inserted directly in output list (@test-evaluate.r#63) 
classes(ev) not equal to c("source", "numeric", "source", "source", "source", "gg").
1/6 mismatches
x[6]: "simpleError"
y[6]: "gg"


2. Failure: ggplot is captured (@test-graphics.r#15) ---------------------------
classes(ev) not equal to c("source", "source", "recordedplot").
1/3 mismatches
x[3]: "simpleError"
y[3]: "recordedplot"


3. Failure: plots in a loop are captured even the changes seem to be from par only (@test-graphics.r#89) 
classes(ev) not equal to c("source", "recordedplot")[c(1, 2, 1, 1, 2, 2, 2)].
Lengths differ: 5 vs 7


4. Failure: an incomplete plot with a comment in the end is also captured (@test-graphics.r#113) 
classes(ev) not equal to rep(c("source", "recordedplot"), c(3, 1)).
2/4 mismatches
x[3]: "simpleError"
y[3]: "source"

x[4]: "source"
y[4]: "recordedplot"


testthat results ================================================================
OK: 46 SKIPPED: 0 FAILED: 4
1. Failure: return value of value handler inserted directly in output list (@test-evaluate.r#63) 
2. Failure: ggplot is captured (@test-graphics.r#15) 
3. Failure: plots in a loop are captured even the changes seem to be from par only (@test-graphics.r#89) 
4. Failure: an incomplete plot with a comment in the end is also captured (@test-graphics.r#113) 

Error: testthat unit tests failed
Execution halted
[[1]]
$src
[1] "x <-"

attr(,"class")
[1] "source"

[[2]]
<simpleError: <text>:2:0: unexpected end of input
1: x <-
   ^>

[[1]]
$src
[1] "structure(1, class = \"FOO_BAR\")"

attr(,"class")
[1] "source"

[[2]]
NULL

> structure(1, class = "FOO_BAR")
NULL

Tests complete      
```

**Comment by yihui** [comment] 2016-09-02 04:40
There is no failure on Travis CI (https://travis-ci.org/yihui/evaluate/builds/157000167), and I cannot reproduce the error locally on Mac, either. Are all your packages up-to-date? What is your version of ggplot2? `devtools::session_info('evaluate')`?

**Comment by adamryczkowski** [comment] 2016-09-02 10:14
I've updated all packages and no change to the output. Here is my `devtools::session_info()`:

```
Session info -----------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, linux-gnu           
 ui       RStudio (0.99.1294)         
 language en_US                       
 collate  en_US.UTF-8                 
 tz       <NA>                        
 date     2016-09-02                  

Packages ---------------------------------------------------------------------------------------------------------------------
 package    * version date       source        
 colorspace   1.2-6   2015-03-11 CRAN (R 3.2.0)
 crayon       1.3.2   2016-06-28 CRAN (R 3.3.1)
 devtools     1.12.0  2016-06-24 CRAN (R 3.3.1)
 digest       0.6.10  2016-08-02 CRAN (R 3.3.1)
 evaluate   * 0.9     2016-09-02 local         
 ggplot2    * 2.1.0   2016-03-01 CRAN (R 3.3.1)
 gtable       0.2.0   2016-02-26 CRAN (R 3.2.4)
 lattice    * 0.20-33 2015-07-14 CRAN (R 3.2.1)
 magrittr     1.5     2014-11-22 CRAN (R 3.2.0)
 memoise      1.0.0   2016-01-29 CRAN (R 3.3.0)
 munsell      0.4.3   2016-02-13 CRAN (R 3.2.4)
 plyr         1.8.4   2016-06-08 cran (@1.8.4) 
 R6           2.1.3   2016-08-19 CRAN (R 3.3.1)
 Rcpp         0.12.6  2016-07-19 CRAN (R 3.3.1)
 scales       0.4.0   2016-02-26 CRAN (R 3.3.0)
 stringi      1.1.1   2016-05-27 CRAN (R 3.3.0)
 stringr      1.1.0   2016-08-19 CRAN (R 3.3.1)
 testthat   * 1.0.2   2016-04-23 CRAN (R 3.3.0)
 withr        1.0.2   2016-06-20 CRAN (R 3.3.1)
```

I do the tests by loading the evaluate's RStudio project and performing the tests via `Ctrl+Shift+T`. RStudio version: 0.99.1294.

**Comment by yihui** [comment] 2016-12-01 07:04
Closing since this is not reproducible to me, on Travis CI, or on CRAN: https://cran.rstudio.com/web/checks/check_results_evaluate.html I have no idea what could be wrong there.

**Closed by yihui** 2016-12-01 07:04 UTC
